# Generated by Django 4.2.4 on 2023-09-12 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.time(14, 0), verbose_name='время начала рассылки')),
                ('end_time', models.TimeField(default=datetime.time(15, 0), verbose_name='время окончания рассылки')),
                ('periodicity', models.DurationField(choices=[(datetime.timedelta(days=1), 'Раз в день'), (datetime.timedelta(days=7), 'Раз в неделю'), (datetime.timedelta(days=30, seconds=43200), 'Раз в месяц')], default=datetime.timedelta(days=30, seconds=43200), verbose_name='периодичность')),
                ('status', models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена')], default='Создана', max_length=50, verbose_name='статус рассылки')),
                ('clients', models.ManyToManyField(to='clients.client', verbose_name='клиенты рассылки')),
            ],
            options={
                'verbose_name': 'настройки рассылки',
                'verbose_name_plural': 'настройки рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, verbose_name='тема письма')),
                ('text', models.TextField(verbose_name='тело письма')),
                ('status', models.CharField(choices=[('К отправке', 'К отправке'), ('Отправлено', 'Отправлено')], default='К отправке', max_length=50, verbose_name='статус отправки')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_list.mailinglistsettings', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('status', models.BooleanField(verbose_name='статус попытки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client', verbose_name='клиент рассылки')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing_list.mailinglistsettings', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'лог',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
