# Generated by Django 4.2.4 on 2023-08-31 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('mailing_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistsettings',
            name='users',
            field=models.ManyToManyField(to='user.user', verbose_name='пользователи'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='mailinglistsettings',
            name='time',
        ),
        migrations.AddField(
            model_name='mailinglistsettings',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='mailinglistsettings',
            name='start_time',
            field=models.TimeField(default=datetime.time(14, 0), verbose_name='время начала рассылки'),
        ),
    ]
