# Generated by Django 4.2.4 on 2023-08-31 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0002_delete_user_remove_mailinglistsettings_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglistsettings',
            name='end_time',
            field=models.TimeField(default=datetime.time(15, 0), verbose_name='время окончания рассылки'),
        ),
    ]
