# Generated by Django 4.2.4 on 2023-09-18 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0002_mailinglistsettings_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailinglistsettings',
            options={'permissions': [('change_status', 'Can turn off mailing list')], 'verbose_name': 'настройки рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
    ]
