# Generated by Django 4.2.4 on 2023-08-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0003_alter_mailinglistsettings_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('К отправке', 'К отправке'), ('Отправлено', 'Отправлено')], default='К отправке', max_length=50, verbose_name='статус отправки'),
        ),
    ]
