# Generated by Django 4.2.4 on 2023-09-02 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options'),
        ('mailing_list', '0004_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.user', verbose_name='клиент рассылки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mailing_list.mailinglistsettings', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='mailinglistsettings',
            name='users',
            field=models.ManyToManyField(to='user.user', verbose_name='клиенты рассылки'),
        ),
    ]
