# Generated by Django 4.2.4 on 2023-09-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0005_log_user_alter_log_mailing_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(auto_created=True, verbose_name='дата и время последней попытки'),
        ),
    ]
