# Generated by Django 4.2.4 on 2023-09-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0007_alter_log_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='response',
        ),
    ]
