# Generated by Django 4.2.4 on 2023-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержимое статьи')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='изображение')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('publish_date', models.DateField(auto_now_add=True, verbose_name='дата публикации')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блог',
            },
        ),
    ]
